// Writes src/data.ts from the sequence tables of the Python package, so both packages read the
// same tables (src/sinhala_orthography/data/*.json in the repository root).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const DATA = path.resolve(here, "../../src/sinhala_orthography/data");
const read = (name) => JSON.parse(fs.readFileSync(path.join(DATA, name), "utf-8"));

const out = `// Generated by scripts/gen-data.mjs from src/sinhala_orthography/data/*.json. Do not edit.

/** [sequence, letter, mode, note] */
export const CONSONANT_TABLE: readonly (readonly [string, string, string, string])[] = ${JSON.stringify(read("consonants.json"))};

/** [sequence, vowel id, independent vowel, sign, mode, note] */
export const VOWEL_TABLE: readonly (readonly [string, string, string, string, string, string])[] = ${JSON.stringify(read("vowels.json"))};

/** [sequence, output, mode, note]; output is ං, ඃ, ඁ or "touch" */
export const SPECIAL_TABLE: readonly (readonly [string, string, string, string])[] = ${JSON.stringify(read("specials.json"))};
`;
fs.writeFileSync(path.join(here, "../src/data.ts"), out);
